title: "Mr Simon C: Yet Another Programming Blog"
description: Work smarter, not necessarily harder.
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

navigation:
- text: Home
  url: index.html
- text: About
  url: about.html